version: "3.8"
services:
  web:
    restart: always
    build: ./web
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=/web/main_api.py
    volumes:
      - "./web:/web"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5